package dev.astriavr.player;

import java.util.regex.Matcher;
import java.util.regex.Pattern;

/** Complete bilingual UI catalog. Arguments are inserted once, never translated or re-parsed. */
public enum AppText {
    LANGUAGE("语言", "Language"),
    LANGUAGE_NAME("简体中文", "English"),
    SETTINGS_STANDARD_VIDEO("普通视频", "Standard video"),
    SETTINGS_AUTO("自动识别", "Auto"),
    SETTINGS_EQ_180("等距柱状 180°", "EQ 180°"),
    SETTINGS_EQ_360("等距柱状 360°", "EQ 360°"),
    SETTINGS_MONO_FISHEYE("单鱼眼 180°", "Fish 180°"),
    SETTINGS_STEREO_FISHEYE("双鱼眼 180°", "3D Fish 180°"),
    SETTINGS_CUBEMAP("Cubemap 3×2", "Cube 3×2"),
    SETTINGS_EAC("EAC 立方体", "EAC"),
    CANCEL("取消", "Cancel"),
    PLAY_PAUSE("播放 / 暂停", "Play / pause"),
    PRESS_ONCE_TO_TOGGLE("每次按下切换一次", "Press once to toggle"),
    SPEED("倍速减 / 加", "Speed − / +"),
    AT_THE_LIMIT_DOUBLE_PRESS_THE("到极限后双击同键恢复 1×", "At the limit, double-press the same button to reset to 1×"),
    LEFT_STICK("左摇杆", "Left stick"),
    LOOK_AROUND("转动视角", "Look around"),
    PUSH_GENTLY_FOR_FINE_CONTROL_FULLY("轻推微调，满推快速转向", "Push gently for fine control, fully for a quick turn"),
    D_PAD("方向键", "D-pad"),
    SEEK_FIELD_OF_VIEW("进度与视场角", "Seek & field of view"),
    REWIND_FORWARD_N_FOV_FOV("← → 快退 / 快进\n↑ 视场角 −，↓ 视场角 ＋", "← → Rewind / forward\n↑ FOV −, ↓ FOV +"),
    RECENTER("视角回正", "Recenter"),
    SET_THE_CURRENT_DIRECTION_AS_FORWARD("将当前朝向设为正前方", "Set the current direction as forward"),
    GYROSCOPE("陀螺仪开关", "Gyroscope"),
    TOGGLE_HEAD_TRACKING("切换头部转向控制", "Toggle head tracking"),
    IPD_NOT_USED("瞳距不使用", "IPD not used"),
    IPD("瞳距减 / 加", "IPD − / +"),
    NO_IPD_ADJUSTMENT_IN_SINGLE_VIEW("单画面无需调瞳距", "No IPD adjustment in single-view mode"),
    CM_PER_STEP_HOLD_TO_REPEAT("每档 0.1 cm，可长按", "0.1 cm per step; hold to repeat"),
    RIGHT_STICK("右摇杆", "Right stick"),
    BRIGHTNESS_VOLUME("亮度与音量", "Brightness & volume"),
    BRIGHTNESS_N_VOLUME("← → 亮度减 / 加\n↑ ↓ 音量加 / 减", "← → Brightness − / +\n↑ ↓ Volume + / −"),
    CONTROLLER_DIAGRAM_LEFT_STICK_AT_UPPER("手柄线图：左摇杆在左上，方向键在左下，右摇杆在右下；Y 上、X 左、B 右、A 下，中间三横线为菜单键。", "Controller diagram: left stick at upper left, D-pad at lower left, right stick at lower right. Y above, X left, B right, A below. The three-line button in the center is Menu."),
    PLAYLIST_CHOOSE_A_VIDEO("播放列表 · 选片", "Playlist · Choose a video"),
    MENU_START_VR_PLAYLIST("MENU / START · 双眼播放列表", "MENU / START · Binocular playlist"),
    TAP_THE_PLAYLIST_ICON_IN_THE("点击上栏列表图标；点击封面续播，更多操作中可移出记录。", "Tap the playlist icon in the top bar, then a cover to resume. Use video actions to remove an entry."),
    MENU_OPEN_CLOSE_SELECT_RESUME("菜单键呼出 / 关闭  ·  ← → 选择视频  ·  ↑ 确认并续播", "Menu: open / close · ← → Select · ↑ Resume"),
    NO_JAVA_EXCEPTIONS_HAVE_BEEN_RECORDED("暂无已捕获的 Java 异常。", "No Java exceptions have been recorded."),
    N_NSYSTEM_EXIT_HISTORY_N("\n\n系统退出记录：\n", "\n\nSystem exit history:\n"),
    ASTRIAVR_ERROR_REPORT("AstriaVR · 错误信息", "AstriaVR · Error report"),
    COPY_THE_ERROR_REPORT_TO_HELP("复制错误信息，便于定位异常。", "Copy the error report to help diagnose the problem."),
    COPY_ERROR_REPORT("复制错误信息", "Copy error report"),
    COPIED("已复制", "Copied"),
    TRY_OPENING_THE_PLAYER_AGAIN("重新尝试打开播放器", "Try opening the player again"),
    UNKNOWN("未知", "Unknown"),
    CHARGING("，正在充电", ", charging"),
    TIME_BATTERY("时间 {0}，电量{1}{2}", "Time {0}, battery {1}{2}"),
    STANDARD_VIDEO_VIEW("普通视频画面", "Standard video view"),
    NOT_STARTED("未启动", "Not started"),
    GYROSCOPE_OFF("陀螺仪关闭", "Gyroscope off"),
    GYROSCOPE_FUSION("陀螺仪融合", "Gyroscope fusion"),
    ROTATION_VECTOR("旋转向量", "Rotation vector"),
    ORIENTATION_SENSOR_UNAVAILABLE("姿态传感器不可用", "Orientation sensor unavailable"),
    BITRATE_F_MBPS("码率 %.2f Mbps", "Rate %.2f Mbps"),
    BITRATE("码率 —", "Rate —"),
    CHOOSE_A_LOCAL_VR_VIDEO("选择一个本地 VR 视频", "Choose a local VR video"),
    LOADING_SETTINGS_AND_INITIALIZING_THE_INTERFACE("读取设置与初始化界面", "Loading settings and initializing the interface"),
    SHOWING_THE_PLAYER("显示播放器界面", "Showing the player"),
    TOGGLE_GYROSCOPE_B("陀螺仪开关 · B", "Toggle gyroscope · B"),
    RECENTER_A("回正 · A", "Recenter · A"),
    RESET_THE_STANDARD_VIDEO_S_SIZE("恢复普通视频的默认大小和位置", "Reset the standard video's size and position"),
    VIEW_RESET("画面已复位", "View reset"),
    SETTINGS("设置", "Settings"),
    PLAYLIST("播放列表", "Playlist"),
    PLAY("播放", "Play"),
    REWIND("快退", "Rewind"),
    FORWARD("快进", "Forward"),
    DECREASE("降低{0}", "Decrease {0}"),
    INCREASE("提高{0}", "Increase {0}"),
    IPD_CM("瞳距 cm", "IPD cm"),
    PLAYBACK_SPEED("播放速度", "Speed"),
    FIELD_OF_VIEW("视场角度", "FOV"),
    THIS_DECODER_CANNOT_CONVERT_HDR_TO("此解码器不支持 HDR 转 SDR，已恢复 HDR 自动输出", "This decoder cannot convert HDR to SDR. Automatic HDR output has been restored."),
    DOLBY_VISION("杜比视界", "Dolby Vision"),
    CURRENT_VIDEO_DOLBY_VISION_N("当前片源：杜比视界\n", "Current video: Dolby Vision\n"),
    CURRENT_VIDEO_HDR_PQ_N("当前片源：HDR（PQ）\n", "Current video: HDR (PQ)\n"),
    CURRENT_VIDEO_HDR_HLG_N("当前片源：HDR（HLG）\n", "Current video: HDR (HLG)\n"),
    CURRENT_VIDEO_SDR_OR_NO_HDR("当前片源：SDR 或未标记 HDR\n", "Current video: SDR or no HDR tag\n"),
    THE_DISPLAY_REPORTS_NO_HDR_SUPPORT("屏幕未报告 HDR 支持", "The display reports no HDR support"),
    DISPLAY_SUPPORTS("屏幕支持：{0}", "Display supports: {0}"),
    NTHIS_ANDROID_VERSION_HANDLES_HDR_AUTOMATICALLY("\n当前系统由设备自动处理 HDR，不支持手动关闭", "\nThis Android version handles HDR automatically; it cannot be turned off manually."),
    DEFAULT("（默认）", " (default)"),
    VIEWING_MODE("观看模式", "Viewing mode"),
    EXIT_DEBUG("关闭调试", "Finish tuning"),
    DEBUG_MODE("调试模式", "Comfort tuning"),
    ENTER_DEBUG_MODE("进入调试模式？", "Adjust viewing comfort?"),
    PAUSE_THE_VIDEO_AND_SHOW_A("暂时暂停视频，显示黑底视场网格和边界线，方便调整镜头参数。\n\n再次播放会自动退出调试，也可在设置里关闭。原视频与进度保留。", "Pause the video and show a field-of-view grid and boundary lines on a black background to help adjust the lenses for a comfortable view.\n\nComfort tuning ends when playback starts, or you can turn it off in Settings. Your video and position are preserved."),
    ENTER_DEBUG("进入调试", "Start tuning"),
    RESET_DEFAULTS("恢复默认", "Reset defaults"),
    RESET_ALL_SETTINGS("恢复默认设置？", "Reset all settings?"),
    RESET_VIEWING_BRIGHTNESS_SPEED_LENS_CORRECTION("将还原观看、亮度、倍速、镜头补偿和操控设置，关闭调试模式，并重新检测屏幕尺寸。\n\n视频文件、播放列表、当前视频与播放进度都会保留。", "Reset viewing, brightness, speed, lens correction and controls, turn off comfort tuning, and detect the screen size again.\n\nYour video files, playlist, current video and playback position are preserved."),
    BACK_TO_PLAYER("返回播放", "Back to player"),
    D_DUAL_LENS_VR("3D 双镜头 · VR", "3D dual lens · VR"),
    PHONE_SINGLE_LENS_VR("手机直看单镜头 · VR", "Phone single lens · VR"),
    STANDARD_VIDEO("普通视频", "2D video"),
    PICTURE("画面", "Picture"),
    PHONE_ASPECT_RATIO("手机画面比例", "Aspect ratio"),
    LETTERBOX("16:9 · 留黑", "16:9 · Letterbox"),
    FULL_SCREEN("真全屏", "Full screen"),
    PHONE_PROJECTION("手机显示投影", "Display shape"),
    DYNAMIC_RECTANGLE("矩形动态", "Dynamic rectangle"),
    ELLIPSE("椭圆", "Ellipse"),
    ULTRAWIDE_CORRECTION_IN_STEPS_EQUALS_THE("超广角动态补偿，每档5%，70%对应旧版100%，100%为增强上限", "Ultrawide correction in 5% steps. 70% equals the previous version's 100%; 100% is the enhanced maximum."),
    CIRCULAR_FIELD_DIAMETER_PER_EYE_TO("单眼圆形视场直径，4至7厘米，每档0.2厘米", "Circular field diameter per eye: 4 to 7 cm, in 0.2 cm steps"),
    SOURCE_PROJECTION("片源投影", "Source projection"),
    AUTO_DETECT_DEFAULT("自动识别（默认）", "Auto (default)"),
    SIDE_BY_SIDE_SBS("左右 SBS", "SBS"),
    TOP_BOTTOM_TB("上下 TB", "TB"),
    MONO("单目", "Mono"),
    VIDEO_LAYOUT("视频布局", "Video layout"),
    EYE_ORDER("左右眼顺序", "Eye order"),
    NORMAL("正常", "Normal"),
    SWAP_EYES("交换左右眼", "Swap eyes"),
    VIEWING_LENS("取景镜头", "Viewing lens"),
    LEFT_LENS("左镜头", "Left lens"),
    RIGHT_LENS("右镜头", "Right lens"),
    LENS_DISTORTION_CORRECTION_TO_IN_STEPS("镜头畸变补偿，0%至100%，每档5%，按圆形视场大小独立保存", "Lens distortion correction: 0% to 100%, in 5% steps. Saved separately for each circular field size."),
    FOR_VR_HEADSETS_USE_FOR_DIRECT("仅用于眼镜盒，手机直看可为0%。", "For headsets only. Use 0% for direct phone viewing."),
    SCREEN_CALIBRATION("屏幕适配", "Screen calibration"),
    CENTER_THE_CIRCULAR_VIEWS_USING_THE("按屏幕实际尺寸，保持圆形视场居中", "Center the views using the screen's physical size"),
    DETECT_AGAIN("重新检测", "Detect again"),
    ENTER_MANUALLY("手动输入", "Enter manually"),
    CONTROLS("操控", "Controls"),
    CHOOSE_HOW_YOU_PREFER_TO_WATCH("选择你习惯的观看方式", "Choose your controls"),
    DRAG_TO_LOOK("拖动视角", "Drag to look"),
    DRAG_WITH_ONE_FINGER_TO_LOOK("单指拖动画面，默认开启", "Drag with one finger to look around. On by default."),
    AUTO_ROTATE("感应旋屏", "Auto-rotate"),
    SWITCH_BETWEEN_LANDSCAPE_ORIENTATIONS_WITH_THE("随手机方向切换左右横屏，默认关闭", "Follow the phone's landscape orientation. Off by default."),
    ON_AUTOMATIC_HDR_OUTPUT_OFF_DISPLAY("开启：自动输出 HDR；关闭：按 SDR 显示", "On: automatic HDR output. Off: display as SDR."),
    TOUCH_AND_ROTATION_SETTINGS_FOR_STANDARD("普通视频的触屏与旋转设置", "Touch and rotation settings for standard video"),
    PINCH_TO_ZOOM("双指放大", "Pinch to zoom"),
    PINCH_TO_ZOOM_AND_DRAG_TO("双指捏合缩放、拖动调整位置，默认开启", "Pinch to zoom and drag to reposition. On by default."),
    AFTER_ZOOMING_TAP_RESET_IN_THE("放大后可点播放上栏的复位按钮恢复原始大小和位置。", "After zooming, tap Reset in the top playback bar to restore the original size and position."),
    TAP_TO_SHOW_OR_HIDE_THE("单击显示或隐藏播放栏；中间双击播放或暂停，左右双击快退或快进。双击左上角停止视频或退出调试。", "Tap to show or hide the playback bars. Double-tap the center to play or pause, or the left / right side to rewind / fast-forward. Double-tap the top-left logo to stop the video or exit comfort tuning."),
    AT_THE_END_OR_WHEN_PAUSED("播放结束或退到片头暂停后，稍作停顿，再双击对应侧画面或快进、快退按钮切换视频。播放列表首尾循环。", "At the end, or when paused at the beginning, wait briefly, then double-tap the corresponding side or seek button to switch videos. The playlist wraps at both ends."),
    CONTROLLER_GUIDE("手柄指南", "Controller guide"),
    BUTTONS_AND_ACTIONS("按键与功能一览", "Buttons and actions"),
    ABOUT("关于", "About"),
    ASTRIAVR_A_NEW_VIEW_OF_YOUR("AstriaVR · 本地视频，换个视角看", "AstriaVR · A new view of your local videos"),
    VERSION_LOCAL_VR_PLAYER_FOR_ANDROID("版本 {0}  ·  Android 本地 VR 播放器", "Version {0} · Local VR player for Android"),
    WHAT_IT_CAN_DO("它能做什么", "What it can do"),
    ASTRIAVR_PLAYS_LOCAL_PANORAMIC_AND_STANDARD("AstriaVR 可以播放本地全景视频，也兼顾普通视频。支持 180° / 360° 全景、左右 SBS、上下 TB 和单目布局，并按观看模式提供鱼眼 180°、立方体和 EAC 投影。可以戴上眼镜双镜头观看，也可以用手机直看。看了一半不用记时间，播放列表会保存进度。", "AstriaVR plays local panoramic and standard videos. It supports 180° / 360° panoramas, SBS, top / bottom and mono layouts, with 180° fisheye, cubemap and EAC projections depending on the viewing mode. Watch through a dual-lens headset or directly on your phone. The playlist remembers where you stopped."),
    HOW_VIDEO_BECOMES_YOUR_VIEW("视频是怎么变成视野的", "How video becomes your view"),
    MEDIA_EXOPLAYER_HANDLES_PLAYBACK_AND_SYSTEM("Media3 / ExoPlayer 负责播放与系统解码器调度，OpenGL ES 2.0 将全景画面映射到左右眼或手机视场。上栏显示实际启用的解码器和实时视频码率；高分辨率、高码率视频能否流畅播放，取决于手机的解码能力和片源格式。", "Media3 / ExoPlayer handles playback and system decoding. OpenGL ES 2.0 maps panoramic video to the two eyes or phone view. The top bar shows the active decoder and live video bitrate. Smooth playback of high-resolution or high-bitrate video depends on your phone's decoding capability and the video format."),
    ADJUST_FOR_A_COMFORTABLE_VIEW("戴着不舒服，先调参数", "Adjust for a comfortable view"),
    IPD_SETS_THE_SPACING_BETWEEN_THE("瞳距决定双眼画面的位置，视场角决定能看多宽，镜头补偿用来适配眼镜的畸变。调试模式会暂停视频，显示网格、边界和中心点，便于对齐；视频实际开始播放时会自动退出调试。参数不是越大越好，适合自己的眼镜和眼睛更重要。", "IPD sets the spacing between the eye views, field of view controls how wide you can see, and lens correction compensates for headset distortion. Comfort tuning pauses the video and shows a grid, boundaries and center points for alignment; it ends when video playback starts. Choose settings that suit your headset and eyes, rather than simply maximizing them."),
    USEFUL_DETAILS("几个容易混淆的小细节", "Useful details"),
    IN_DUAL_LENS_MODE_PRESS_MENU("双镜头模式按菜单键可打开双眼同步显示的播放列表。播放结束或退到片头暂停后，稍作停顿，再双击对应侧画面或快进、快退按钮，可按列表顺序切换视频，首尾循环。移出播放记录不会删除原文件；文件移动或授权失效时，重新添加即可。", "In dual-lens mode, press Menu to open the playlist in both eyes. At the end, or when paused at the beginning, wait briefly, then double-tap the corresponding side or seek button to move through the playlist, wrapping at both ends. Removing an entry does not delete the original file. Add a video again if it has moved or access has expired."),
    THIS_SCREEN_SUPPORTS_CIRCULAR_VIEWS_UP("当前屏幕最多支持 {0} cm 圆形视场", "This screen supports circular views up to {0} cm"),
    DEFAULT_SETTINGS_RESTORED("已恢复默认设置", "Default settings restored"),
    FIELD_DIAMETER_ADJUSTED_TO_CM("视场已适配为 {0} cm", "Field diameter adjusted to {0} cm"),
    SCREEN_DETECTION_INCOMPLETE("屏幕参数检测未完成", "Screen detection incomplete"),
    N_NENTER_THE_SCREEN_S_PHYSICAL("{0}\n\n可以输入屏幕实际长边和短边（厘米），或使用6.8英寸、20:9默认参数。", "{0}\n\nEnter the screen's physical long and short edges in centimeters, or use the 6.8-inch, 20:9 defaults."),
    USE_DEFAULTS("使用默认", "Use defaults"),
    ENTER_THE_ILLUMINATED_SCREEN_SIZE_EXCLUDING("填写屏幕发光区域尺寸，不含边框；最多两位小数（0.01cm）。", "Enter the illuminated screen size, excluding the bezel, with up to two decimal places (0.01 cm)."),
    LONG_EDGE_CM("屏幕长边（cm）", "Long edge (cm)"),
    SHORT_EDGE_CM("屏幕短边（cm）", "Short edge (cm)"),
    CUSTOM_SCREEN_SIZE("自定义屏幕参数", "Custom screen size"),
    SAVE_APPLY("保存并应用", "Save & apply"),
    ENTER_A_VALUE_ABOVE_AND_UP("请输入大于0且不超过50的厘米值，最多两位小数", "Enter a value above 0 and up to 50 cm, with at most two decimal places"),
    ENTER_A_VALUE_ABOVE_AND_UP_151("请输入大于0且不超过35的厘米值，最多两位小数", "Enter a value above 0 and up to 35 cm, with at most two decimal places"),
    THE_LONG_EDGE_MUST_BE_AT("长边不能小于短边", "The long edge must be at least as long as the short edge"),
    THIS_SIZE_CANNOT_FIT_THE_MINIMUM("此尺寸放不下最小4cm双眼视场，请核对屏幕尺寸", "This size cannot fit the minimum 4 cm dual-eye views. Check the screen dimensions."),
    COULD_NOT_READ_THE_SYSTEM_S("无法读取系统屏幕参数。", "Could not read the system's screen parameters."),
    THE_SYSTEM_DID_NOT_PROVIDE_VALID("系统未提供有效物理DPI。", "The system did not provide valid physical DPI values."),
    THE_APP_IS_NOT_USING_THE("当前不是完整屏幕显示，无法准确换算。", "The app is not using the full screen, so its physical size cannot be calculated accurately."),
    THE_DETECTED_SIZE_CM_CANNOT_FIT("检测尺寸 {0} × {1}cm 放不下当前双眼视场。", "The detected size, {0} × {1} cm, cannot fit the current dual-eye views."),
    SYSTEM_RESOLUTION_D_D_PX_NPHYSICAL("系统分辨率：%d × %d px\n物理DPI：X %.1f / Y %.1f\n屏幕：%.2f × %.2f cm，%.2f英寸\n\n系统报告可能有误，可在设置中手动修改。", "System resolution: %d × %d px\nPhysical DPI: X %.1f / Y %.1f\nScreen: %.2f × %.2f cm, %.2f inches\n\nSystem values may be inaccurate. You can adjust them manually in Settings."),
    DETECTED_SCREEN_SIZE("屏幕检测结果", "Detected screen size"),
    APPLY("应用", "Apply"),
    CONTROLLER_CONNECTED_BACK_WILL_NOT_EXIT("手柄已连接，已阻止返回退出", "Controller connected; Back will not exit playback"),
    SINGLE_LENS_VR("单镜头 VR", "Single-lens VR"),
    DUAL_LENS_VR("双镜头 VR", "Dual-lens VR"),
    PHONE_SINGLE_LENS_VR_164("手机直看单镜头 VR", "Phone single-lens VR"),
    D_DUAL_LENS_VR_165("3D 双镜头 VR", "3D dual-lens VR"),
    VIEWING_MODE_166("观看模式：{0}", "Viewing mode: {0}"),
    ULTRAWIDE_CORRECTION("超广角动态补偿  {0}%", "Ultrawide correction  {0}%"),
    CIRCULAR_FIELD_PER_EYE_CM("单眼圆形视场  {0} cm", "Circular field per eye  {0} cm"),
    CM("{0}厘米", "{0} cm"),
    S_SCREEN_F_F_CM_NDIAMETER("%s · 屏幕 %.2f × %.2f cm\n圆形直径 %.1f cm · 瞳距 %.1f–%.1f cm", "%s · Screen %.2f × %.2f cm\nDiameter %.1f cm · IPD %.1f–%.1f cm"),
    DETECTED_SCREEN_SIZE_APPLIED("已应用检测参数", "Detected screen size applied"),
    DEFAULT_INCHES("原始参数：6.8英寸 / 20:9", "Default: 6.8 inches / 20:9"),
    HORIZONTAL_FIELD_OF_VIEW_DEGREES("水平视角 {0}度", "Horizontal field of view {0} degrees"),
    FIELD_OF_VIEW_DEGREES("视场角度 {0}度", "Field of view {0} degrees"),
    LENS_DISTORTION_CORRECTION("镜头畸变补偿  {0}%", "Lens distortion correction  {0}%"),
    AUTO("自动 · ", "Auto · "),
    AUTO_177("自动 · {0}", "Auto · {0}"),
    ON("已开启  ✓", "On  ✓"),
    OFF("未开启", "Off"),
    SOURCE_PROJECTION_180("片源投影 {0}，{1}", "Source projection: {0}, {1}"),
    UNKNOWN_PROJECTION_TAG_CHOOSE_THE_SOURCE("无法识别此投影标记，请在设置中选择片源投影", "Unknown projection tag. Choose the source projection in Settings."),
    COULD_NOT_OPEN_THE_FILE_PICKER("无法打开文件选择器：{0}", "Could not open the file picker: {0}"),
    ADDING_VIDEOS("正在添加 {0} 个视频…", "Adding {0} videos…"),
    LOCAL_VIDEO("本地视频", "Local video"),
    PROCESSED_VIDEOS_DUPLICATE_FILES_ARE_SKIPPED("已处理 {0} / {1} 个视频，重复文件不会重复添加", "Processed {0} / {1} videos. Duplicate files are skipped."),
    NPERSISTENT_ACCESS_WAS_NOT_GRANTED_FOR("\n{0} 个文件未获得长期授权，失效后需重新选择", "\nPersistent access was not granted for {0} files. Select them again if access expires."),
    COULD_NOT_SAVE_PLAYBACK_HISTORY_CHECK("无法保存播放记录，请检查存储空间", "Could not save playback history. Check available storage."),
    THE_FILE_HAS_MOVED_OR_ACCESS("文件已移动或授权失效，请通过“打开视频”重新选择", "The file has moved or access has expired. Add it again from the playlist."),
    THIS_DEVICE_CANNOT_DECODE_THE_VIDEO("设备无法解码此片源，可尝试较低分辨率的 H.264 / H.265 视频", "This device cannot decode the video. Try a lower-resolution H.264 / H.265 file."),
    TAP_PLAY_TO_RETRY_OR_SELECT("点击播放重试，或重新选择文件", "Tap Play to retry, or select the file again"),
    CANNOT_PLAY("无法播放：{0}", "Cannot play: {0}"),
    S("{0} {1} 秒 · ", "{0} {1} s · "),
    COULD_NOT_READ_THE_PLAYLIST_TRY("无法读取播放列表，请重试", "Could not read the playlist. Try again."),
    THE_PLAYLIST_IS_EMPTY("播放列表为空", "The playlist is empty"),
    NEXT("下一个", "Next"),
    PREVIOUS("上一个", "Previous"),
    IPD_F_CM("瞳距 %.1f cm", "IPD %.1f cm"),
    RECENTERED("已回正", "Recentered"),
    GYROSCOPE_CONTROL_ON("陀螺仪控制已开启", "Gyroscope control on"),
    GYROSCOPE_CONTROL_OFF_USE_THE_LEFT("陀螺仪控制已关闭 · 左摇杆转向", "Gyroscope control off · Use the left stick to look around"),
    SPEED_X("倍速 {0}x", "Speed {0}x"),
    HORIZONTAL_FOV("水平视角 {0}°", "Horizontal FOV {0}°"),
    FOV("视角 {0}°", "FOV {0}°"),
    VOLUME("音量 {0}/{1}", "Volume {0}/{1}"),
    BRIGHTNESS("亮度 {0}%", "Brightness {0}%"),
    CHOOSE_A_VIDEO_TO_PLAY("选择一个视频播放", "Choose a video to play"),
    FIELD_OF_VIEW_DEBUG("视场调试", "Comfort tuning"),
    DECODER("解码器：{0}", "Decoder: {0}"),
    DECODER_INACTIVE("解码器：未启用", "Decoder: inactive"),
    LOADING_PLAYBACK_HISTORY("正在读取播放记录…", "Loading playback history…"),
    BUFFERING("正在缓冲…", "Buffering…"),
    PLAYBACK_EXITS_DEBUG_MODE_OR_DOUBLE("视频开始播放后退出调试 · 双击左上角也可退出", "Playback exits comfort tuning · Or double-tap the top-left logo"),
    RETRY("重试", "Retry"),
    PAUSE("暂停", "Pause"),
    TURN_GYROSCOPE_OFF_B("关闭陀螺仪 · B", "Turn gyroscope off · B"),
    TURN_GYROSCOPE_ON_B("开启陀螺仪 · B", "Turn gyroscope on · B"),
    ON_217("已开启", "On"),
    OFF_218("已关闭", "Off"),
    COULD_NOT_SAVE_PLAYBACK_POSITION_CHECK("播放进度保存失败，请检查存储空间", "Could not save playback position. Check available storage."),
    BITRATE_MBPS("码率 9999.99 Mbps", "Rate 9999.99 Mbps"),
    SEARCH_VIDEO_NAMES("搜索视频名称", "Search video names"),
    SEARCH_VIDEOS("搜索视频", "Search videos"),
    SWITCH_TO_COVER_VIEW("切换为封面模式", "Switch to cover view"),
    ADD_VIDEOS("添加视频", "Add videos"),
    CLOSE_SEARCH("关闭搜索", "Close search"),
    SWITCH_TO_LIST_VIEW("切换为列表模式", "Switch to list view"),
    LOADING_PLAYLIST("正在读取列表…", "Loading playlist…"),
    COULD_NOT_LOAD_THE_PLAYLIST_GO("列表读取失败，请返回后重试", "Could not load the playlist. Go back and try again."),
    COULD_NOT_LOAD_THE_PLAYLIST_TRY("列表读取失败，请重试", "Could not load the playlist. Try again."),
    YOUR_PLAYLIST_IS_EMPTY_NTAP_AT("列表为空\n点击右上角＋添加视频", "Your playlist is empty\nTap + at the top right to add videos"),
    NO_MATCHING_VIDEOS_NTRY_ANOTHER_NAME("没有找到匹配的视频\n试试其他名称，或关闭搜索", "No matching videos\nTry another name or close search"),
    REMOVED_FROM_PLAYLIST_ORIGINAL_FILE_KEPT("已移出列表 · 原视频仍保留", "Removed from playlist · Original file kept"),
    COULD_NOT_SAVE_THE_ORDER_TRY("未能保存顺序，请重试", "Could not save the order. Try again."),
    PLAY_DURATION_LONG_PRESS_FOR_VIDEO("播放 {0}，总时长 {1}。长按打开视频操作", "Play {0}, duration {1}. Long-press for video actions."),
    RESUME_PLAYBACK("继续播放", "Resume playback"),
    VIDEO_ACTIONS("视频操作", "Video actions"),
    PLAY_237("播放 {0}", "Play {0}"),
    VIDEO("视频", "Video"),
    RESUME_AT("继续 {0}", "Resume at {0}"),
    NOT_PLAYED("未播放", "Not played"),
    LOADING_DETAILS("读取信息中…", "Loading details…"),
    LONG_PRESS_AND_DRAG_TO_REORDER("{0}，{1}，{2}。长按拖动排序", "{0}, {1}, {2}. Long-press and drag to reorder."),
    CLOSE_ACTION_PANEL("关闭操作面板", "Close action panel"),
    PLAY_FROM_START("从头播放", "Play from start"),
    RETURN_TO_THE_BEGINNING("回到视频开头", "Return to the beginning"),
    REFRESH_COVER("更新封面", "Refresh cover"),
    CAPTURE_A_NEW_VIDEO_FRAME("重新截取视频画面", "Capture video frame"),
    CAPTURE_A_NEW_FORWARD_VIEW_FROM("重新截取右眼正前方画面", "Capture right-eye front view"),
    COULD_NOT_REFRESH_THE_COVER_TRY("更新封面失败，请重试", "Could not refresh the cover. Try again."),
    REMOVE_FROM_PLAYLIST("移出播放列表", "Remove from playlist"),
    REMOVE_THE_ENTRY_AND_KEEP_THE("只移除记录，保留原视频", "Remove entry; keep file"),
    COULD_NOT_REMOVE_THE_ENTRY_TRY("移出失败，请重试", "Could not remove the entry. Try again."),
    VIDEO_DETAILS("视频详细信息", "Video details"),
    VIDEO_ACTIONS_254("视频操作，{0}", "Video actions, {0}"),
    ASTRIAVR_DOUBLE_TAP_TO_STOP_THE("AstriaVR，双击停止当前视频或退出调试模式", "AstriaVR. Double-tap to stop the current video or exit comfort tuning."),
    FILE_SIZE_N("文件大小：{0}\n", "File size: {0}\n"),
    DURATION_N("总时长：{0}\n", "Duration: {0}\n"),
    PLAYBACK_POSITION_N("播放进度：{0}\n", "Playback position: {0}\n"),
    VIDEO_CODEC_N("视频编码：{0}\n", "Video codec: {0}\n"),
    LOADING_RESOLUTION_FRAME_RATE_AND_AUDIO("正在读取分辨率、帧率及音频信息…\n", "Loading resolution, frame rate and audio details…\n"),
    RESOLUTION_N("分辨率：{0}\n", "Resolution: {0}\n"),
    NOT_PROVIDED("未提供", "Not provided"),
    FRAME_RATE_N("帧率：{0}\n", "Frame rate: {0}\n"),
    NOMINAL_VIDEO_BITRATE_F_MBPS_N("视频标称码率：%.2f Mbps\n", "Nominal video bitrate: %.2f Mbps\n"),
    AVERAGE_FILE_BITRATE_INCLUDING_AUDIO_F("文件平均码率（含音频）：%.2f Mbps\n", "Average file bitrate (including audio): %.2f Mbps\n"),
    ROTATION_N("旋转角度：{0}°\n", "Rotation: {0}°\n"),
    NO_AUDIO_TRACK_DETECTED("未检测到音轨", "No audio track detected"),
    AUDIO_N("音频：{0}\n", "Audio: {0}\n"),
    AUDIO_TRACKS_N("音轨数量：{0}\n", "Audio tracks: {0}\n"),
    CHANNELS_N("声道数：{0}\n", "Channels: {0}\n"),
    SAMPLE_RATE_HZ_N("采样率：{0} Hz\n", "Sample rate: {0} Hz\n"),
    FILE_LOCATION("文件位置：{0}", "File location: {0}"),
    UNKNOWN_CODEC("编码未知", "Unknown codec"),
    UNKNOWN_SIZE("大小未知", "Unknown size"),
    MONO_FISHEYE("单鱼眼 180°", "Fish 180°"),
    STEREO_FISHEYE("双鱼眼 180°", "3D fish 180°"),
    EAC_CUBEMAP("EAC 立方体", "EAC cubemap"),
    EQUIRECTANGULAR("等距柱状 360°", "EQ 360°"),
    EQUIRECTANGULAR_279("等距柱状 180°", "EQ 180°"),
    AUTO_DETECT("自动识别", "Auto-detect"),
    MANUAL_SELECTION("手动选择", "Manual selection"),
    VIDEO_METADATA("视频标记", "Video metadata"),
    FILE_NAME("文件名", "File name"),
    ESTIMATED_FROM_ASPECT_RATIO("比例推测", "Estimated from aspect ratio"),
    UNRECOGNIZED_USING("未识别，按180°", "Unrecognized; using 180°"),
    THIS_PROJECTION_TAG_IS_NOT_YET(" · 此投影标记暂不支持", " · This projection tag is not yet supported"),
    APPLICATION_STARTUP("Application 启动", "Application startup"),
    N_N_ANDROID_API_N_PHASE("\n                {0}\n                {1} {2} / Android {3} / API {4}\n                阶段：{5}\n                线程：{6}\n                时间：{7}\n\n                {8}\n            ", "\n                {0}\n                {1} {2} / Android {3} / API {4}\n                Phase: {5}\n                Thread: {6}\n                Time: {7}\n\n                {8}\n            "),
    VR_PLAYLIST_LEFT_RIGHT_TO("双眼播放列表：左右选择，上键播放，菜单键退出，也可触屏关闭", "Binocular playlist: left / right to select, up to play, Menu to exit. You can also tap to close."),
    COULD_NOT_LOAD_PLAYLIST("列表读取失败", "Could not load playlist"),
    PLAYLIST_IS_EMPTY("列表为空", "Playlist is empty"),
    CLOSE_AND_TRY_AGAIN("请关闭后重试", "Close and try again"),
    ADD_VIDEOS_ON_THE_PLAYLIST_PAGE("请先在播放列表页面添加视频", "Add videos on the playlist page first"),
    SELECT_PLAY("{0} / {1}    ← → 选择  ↑ 播放", "{0} / {1}    ← → Select  ↑ Play"),
    MENU_TO_EXIT("菜单键退出", "Menu to exit"),
    MENU_CLOSE("MENU 关闭", "MENU Close"),
    SELECTING_EGL_CONFIGURATION("选择 EGL 配置", "Selecting EGL configuration"),
    NO_RGB_WINDOW_CONFIGURATION_SUPPORTS_OPENGL("找不到支持 OpenGL ES 2 的 RGB888 窗口配置，EGL=0x{0}", "No RGB888 window configuration supports OpenGL ES 2. EGL=0x{0}"),
    COULD_NOT_READ_EGL_CONFIGURATION("读取 EGL 配置失败", "Could not read EGL configuration"),
    CREATING_GL_VIDEO_TEXTURES_AND_SHADERS("创建 GL 视频纹理与着色器", "Creating GL video textures and shaders"),
    THE_GPU_DOES_NOT_SUPPORT_EXTERNAL("GPU 不支持视频外部纹理", "The GPU does not support external video textures"),
    VR_RENDERER_INITIALIZATION_FAILED("VR 渲染初始化失败：{0}", "VR renderer initialization failed: {0}"),
    DRAWING_VR_FRAME("绘制VR画面", "Drawing VR frame"),
    COULD_NOT_UPDATE_VIDEO_TEXTURE("视频纹理更新失败：{0}", "Could not update video texture: {0}");

    private static volatile boolean english = false;
    private static final Pattern ARGUMENT = Pattern.compile("\\{(\\d+)\\}");
    private final String chinese;
    private final String translated;

    AppText(String chinese, String translated) {
        this.chinese = chinese;
        this.translated = translated;
    }

    public static boolean isEnglish() { return english; }
    public static void setEnglish(boolean value) { english = value; }

    public String text(Object... arguments) {
        String template = english ? translated : chinese;
        if (arguments.length == 0) return template;
        Matcher matcher = ARGUMENT.matcher(template);
        StringBuffer output = new StringBuffer();
        while (matcher.find()) {
            int index = Integer.parseInt(matcher.group(1));
            matcher.appendReplacement(output, Matcher.quoteReplacement(String.valueOf(arguments[index])));
        }
        matcher.appendTail(output);
        return output.toString();
    }
}
